load("@rules_python//sphinxdocs:sphinx_docs_library.bzl", "sphinx_docs_library")

sphinx_docs_library(
    name = "blog",
    srcs = [
        "2026/03/delete/index.rst",
        "2026/03/overlines/index.rst",
        "2026/03/rotation/index.rst",
        "2026/04/tapestry/index.rst",
        "index.rst",
    ],
    prefix = "blog/",
    deps = [
        "//src/blog/2026/07/elm:elm_docs",
        "//src/blog/2026/07/elm:elm_static",
    ],
    visibility = ["//visibility:public"],
)
