load("@rules_python//sphinxdocs:sphinx_docs_library.bzl", "sphinx_docs_library")

sphinx_docs_library(
    name = "blog",
    srcs = [
        "2026/03/delete/index.rst",
        "2026/03/overlines/index.rst",
        "2026/03/rotation/index.rst",
        "2026/04/tapestry/index.rst",
        # sentinel
        "index.rst",
    ],
    prefix = "blog/",
    visibility = ["//visibility:public"],
    deps = [
        "//src/blog/2026/07/elm",
        "//src/blog/2026/07/elm:extra"
    ],
)
