load("@rules_python//sphinxdocs:sphinx.bzl", "sphinx_build_binary", "sphinx_docs")
load("@rules_python//sphinxdocs:sphinx_docs_library.bzl", "sphinx_docs_library")

sphinx_docs_library(
    name = "srcs",
    srcs = [
        "index.rst",
        "//src/blog",
        "//src/math",
    ],
    deps = [
        "//src/blog/2026/07/elm:elm_docs",
        "//src/blog/2026/07/elm:elm_static",
    ],
)

sphinx_build_binary(
    name = "sphinx",
    deps = ["@pypi//sphinx"]
)

sphinx_docs(
    name = "src",
    config = "conf.py",
    formats = ["html"],
    sphinx = ":sphinx",
    strip_prefix = "src/",
    visibility = ["//visibility:public"],
    deps = [":srcs"],
    extra_opts = ["--fail-on-warning"],
)
